name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps (Open3D runtime)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            libegl1 \
            libxext6 \
            libxrender1 \
            libx11-6 \
            libgl1-mesa-glx \
            libxkbcommon0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Lint (core errors only)
        run: |
          ruff check --select E9,F63,F7,F82 .

      - name: Run tests
        run: |
          pytest -q
